### ISSUE TITLE
Use ``transaction.interfaces.TransientError`` rather than ``ZODB.POSException.ConflictError``

### ISSUE THREAD

**Issue by jimfulton** [repoze/repoze.retry#4]
`transaction.interfaces.TransientError` indicates that a transactions should be retried.  It's a generalization of ConflictError provided so that tools like `repoze.retry` don't have to depend on ZODB.

I'm in the process of making ZEO `ClientDisconnected` errors transient errors so that short disconnection due to server restart don't necessarily result in client errors.

(Someone should have fixed `ZPublisher.Publish.Retry` to subclass `TransientError` a long time ago. :( )

**Comment by tseaver** [comment]
Thanks for the report!  The current dependencies are "soft":  we don't barf if `ZODB` or `ZPublisher.Publish` cannot be imported.  They are used only for creating the default set of exceptions to be caught and retried.

We could add another "soft" dependency to pull in `transaction.interfaces.TransientError`, but I think we'd need to leave the current ones in place too, so that folks could use the middleware with older versions of ZODB / Zope.

**Comment by jimfulton** [comment]
Fair enough, although ``ConflictError`` has subclassed ``TransientError`` since ZODB 3.10 which was released in 2010. <shrug>

I wasn't suggesting that repose.retry should stop checking ``Retry``, only pointing out that someone should go fix Retry :)
